name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test -v=n
    - name: Run program in debug mode
      run: cd Assignment && dotnet run
    - name: Run program in release mode
      run: |
        cd Assignment
        dotnet publish Release -o out
        cd out
        dotnet Assignment.dll
    - name: Check created logs
      run: |
        cd ./Assignment/out/Logs
        ls -l
        cat *.log

